/* Generated by Yosys 0.53+3 (git sha1 6378ba10e, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "ha.v:1.1-13.10" *)
module ha(a, b, s, c);
  (* src = "ha.v:3.12-3.13" *)
  input a;
  wire a;
  (* src = "ha.v:4.12-4.13" *)
  input b;
  wire b;
  (* src = "ha.v:6.13-6.14" *)
  output c;
  wire c;
  (* src = "ha.v:5.13-5.14" *)
  output s;
  wire s;
  assign s = b ^ a;
  assign c = b & a;
endmodule
