/* Generated by Yosys 0.53+3 (git sha1 6378ba10e, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "clk_divider.v:1.1-42.10" *)
module clk_divider(clk, rst, clk_div2, clk_div4, clk_div8);
  (* src = "clk_divider.v:11.1-22.4" *)
  wire _0_;
  (* src = "clk_divider.v:3.12-3.15" *)
  input clk;
  wire clk;
  (* src = "clk_divider.v:5.12-5.20" *)
  output clk_div2;
  reg clk_div2;
  (* src = "clk_divider.v:6.12-6.20" *)
  output clk_div4;
  wire clk_div4;
  (* src = "clk_divider.v:7.12-7.20" *)
  output clk_div8;
  wire clk_div8;
  (* src = "clk_divider.v:4.12-4.15" *)
  input rst;
  wire rst;
  assign _0_ = ~clk_div2;
  (* src = "clk_divider.v:11.1-22.4" *)
  always @(posedge clk, posedge rst)
    if (rst) clk_div2 <= 1'h0;
    else clk_div2 <= _0_;
  assign clk_div4 = 1'h0;
  assign clk_div8 = 1'h0;
endmodule
