/* Generated by Yosys 0.53+3 (git sha1 6378ba10e, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "fa.v:1.1-14.10" *)
module fa(a, b, cin, s, cout);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "fa.v:3.12-3.13" *)
  input a;
  wire a;
  (* src = "fa.v:4.12-4.13" *)
  input b;
  wire b;
  (* src = "fa.v:5.12-5.15" *)
  input cin;
  wire cin;
  (* src = "fa.v:7.13-7.17" *)
  output cout;
  wire cout;
  (* src = "fa.v:6.13-6.14" *)
  output s;
  wire s;
  assign _02_ = b ^ a;
  assign s = _02_ ^ cin;
  assign _03_ = b & a;
  assign _04_ = cin & b;
  assign _00_ = _04_ | _03_;
  assign _01_ = cin & a;
  assign cout = _01_ | _00_;
endmodule
