/* Generated by Yosys 0.53+3 (git sha1 6378ba10e, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "mux_2_1.v:1.1-9.10" *)
module mux_2_1(a, b, select, y);
  (* src = "mux_2_1.v:2.9-2.10" *)
  input a;
  wire a;
  (* src = "mux_2_1.v:3.9-3.10" *)
  input b;
  wire b;
  (* src = "mux_2_1.v:4.9-4.15" *)
  input select;
  wire select;
  (* src = "mux_2_1.v:5.10-5.11" *)
  output y;
  wire y;
  assign y = select ? b : a;
endmodule
