/* Generated by Yosys 0.53+3 (git sha1 6378ba10e, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "nand_gate.v:1.1-11.10" *)
module nand_gate(a, b, y);
  (* src = "nand_gate.v:3.12-3.13" *)
  input a;
  wire a;
  (* src = "nand_gate.v:4.12-4.13" *)
  input b;
  wire b;
  (* src = "nand_gate.v:5.13-5.14" *)
  output y;
  wire y;
  assign y = ~(b & a);
endmodule
