/* Generated by Yosys 0.53+3 (git sha1 6378ba10e, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "alu_2bit.v:1.1-22.10" *)
module alu_2bit(a, b, sel, result);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  (* src = "alu_2bit.v:3.13-3.14" *)
  input [1:0] a;
  wire [1:0] a;
  (* src = "alu_2bit.v:4.13-4.14" *)
  input [1:0] b;
  wire [1:0] b;
  (* src = "alu_2bit.v:6.18-6.24" *)
  output [2:0] result;
  wire [2:0] result;
  (* src = "alu_2bit.v:5.13-5.16" *)
  input [1:0] sel;
  wire [1:0] sel;
  assign _00_ = a[0] & b[0];
  assign _01_ = ~(sel[0] | sel[1]);
  assign _02_ = sel[0] & sel[1];
  assign _03_ = sel[1] & ~(sel[0]);
  assign _04_ = _03_ | _02_;
  assign _05_ = ~(a[0] | b[0]);
  assign _06_ = _05_ | _00_;
  assign _07_ = _04_ & ~(_06_);
  assign _08_ = sel[0] & ~(sel[1]);
  assign _09_ = _08_ & ~(_05_);
  assign _10_ = _09_ | _07_;
  assign result[0] = _01_ ? _00_ : _10_;
  assign _11_ = a[1] & b[1];
  assign _12_ = ~a[1];
  assign _13_ = b[0] ^ b[1];
  assign _14_ = _02_ ? b[1] : _13_;
  assign _15_ = _14_ ^ _12_;
  assign _16_ = b[0] & ~(a[0]);
  assign _17_ = _16_ ^ _15_;
  assign _18_ = _04_ & ~(_17_);
  assign _19_ = ~(a[1] | b[1]);
  assign _20_ = _08_ & ~(_19_);
  assign _21_ = _20_ | _18_;
  assign result[1] = _01_ ? _11_ : _21_;
  assign _22_ = ~(b[0] | b[1]);
  assign _23_ = _22_ | _02_;
  assign _24_ = _14_ | _12_;
  assign _25_ = _15_ & ~(_16_);
  assign _26_ = _24_ & ~(_25_);
  assign _27_ = ~(_26_ ^ _23_);
  assign _28_ = _27_ & _04_;
  assign result[2] = _28_ & ~(_01_);
endmodule
