/* Generated by Yosys 0.53+3 (git sha1 6378ba10e, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "inverter.v:1.1-10.10" *)
module inverter(a, y);
  (* src = "inverter.v:3.12-3.13" *)
  input a;
  wire a;
  (* src = "inverter.v:4.13-4.14" *)
  output y;
  wire y;
  assign y = ~a;
endmodule
