/* Generated by Yosys 0.53+3 (git sha1 6378ba10e, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

(* top =  1  *)
(* src = "four_bit_comp.v:1.1-15.10" *)
module four_bit_comp(a, b, equal, greater, less);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "four_bit_comp.v:3.18-3.19" *)
  input [3:0] a;
  wire [3:0] a;
  (* src = "four_bit_comp.v:4.18-4.19" *)
  input [3:0] b;
  wire [3:0] b;
  (* src = "four_bit_comp.v:5.13-5.18" *)
  output equal;
  wire equal;
  (* src = "four_bit_comp.v:6.13-6.20" *)
  output greater;
  wire greater;
  (* src = "four_bit_comp.v:7.13-7.17" *)
  output less;
  wire less;
  assign _00_ = ~(a[0] ^ b[0]);
  assign _01_ = ~(a[1] ^ b[1]);
  assign _02_ = _01_ & _00_;
  assign _03_ = ~(a[3] ^ b[3]);
  assign _04_ = a[2] ^ b[2];
  assign _05_ = _04_ | ~(_03_);
  assign equal = _02_ & ~(_05_);
  assign _06_ = b[3] | ~(a[3]);
  assign _07_ = b[2] | ~(a[2]);
  assign _08_ = _03_ & ~(_07_);
  assign _09_ = _06_ & ~(_08_);
  assign _10_ = b[1] | ~(a[1]);
  assign _11_ = b[0] & ~(a[0]);
  assign _12_ = _01_ & ~(_11_);
  assign _13_ = _10_ & ~(_12_);
  assign _14_ = ~(_13_ | _05_);
  assign less = _09_ & ~(_14_);
  assign greater = ~(less | equal);
endmodule
